/* Common */



/* PANEL */
export const PANEL_LEFT_SHOW_HIDE_CLICK = "PANEL_LEFT_SHOW_HIDE_CLICK";

/* AUTH */
export const AUTHORIZE_TOKEN = "AUTHORIZE_TOKEN";
export const AUTHORIZE_TOKEN_SUCCESS = "AUTHORIZE_TOKEN_SUCCESS";
export const AUTHORIZE_TOKEN_ERROR = "AUTHORIZE_TOKEN_ERROR";
export const REVOKE_TOKEN = "REVOKE_TOKEN";
export const REVOKE_TOKEN_SUCCESS = "REVOKE_TOKEN_SUCCESS";
export const REVOKE_TOKEN_ERROR = "REVOKE_TOKEN_ERROR";
export const GET_USER_NAME = "GET_USER_NAME";
export const GET_USER_NAME_SUCCESS = "GET_USER_NAME_SUCCESS";
export const GET_USER_NAME_ERROR = "GET_USER_NAME_ERROR";
export const GET_USER_INFO = "GET_USER_INFO";
export const GET_USER_INFO_SUCCESS = "GET_USER_INFO_SUCCESS";
export const GET_USER_INFO_ERROR = "GET_USER_INFO_ERROR";

export const SET_TENANT_PREFIX = "SET_TENANT_PREFIX";

/* ARTICLE_CREATE */
export const CREATE_ARTICLE = "CREATE_ARTICLE";
export const CREATE_ARTICLE_SUCCESS = "CREATE_ARTICLE_SUCCESS";
export const CREATE_ARTICLE_ERROR = "CREATE_ARTICLE_ERROR";
export const CREATE_ARTICLE_CLEAR_DATA = "CREATE_ARTICLE_CLEAR_DATA";

/* NEWS_FEED */
export const GET_NEWS_ITEMS = "GET_NEWS_ITEMS";
export const GET_NEWS_ITEMS_SUCCESS = "GET_NEWS_ITEMS_SUCCESS";
export const GET_NEWS_ITEMS_ERROR = "GET_NEWS_ITEMS_ERROR";

export const GET_NEWS_ITEMS_COMMENTS = "GET_NEWS_ITEMS_COMMENTS";
export const GET_NEWS_ITEMS_COMMENTS_SUCCESS = "GET_NEWS_ITEMS_COMMENTS_SUCCESS";
export const GET_NEWS_ITEMS_COMMENTS_ERROR = "GET_NEWS_ITEMS_COMMENTS_ERROR";

export const GET_NEWS_ITEMS_CONTACT_LIKES = "GET_NEWS_ITEMS_CONTACT_LIKES";
export const GET_NEWS_ITEMS_CONTACT_LIKES_SUCCESS = "GET_NEWS_ITEMS_CONTACT_LIKES_SUCCESS";
export const GET_NEWS_ITEMS_CONTACT_LIKES_ERROR = "GET_NEWS_ITEMS_CONTACT_LIKES_ERROR";

export const POST_NEWS_ITEMS_COMMENTS = "POST_NEWS_ITEMS_COMMENTS";
export const POST_NEWS_ITEMS_COMMENTS_SUCCESS = "POST_NEWS_ITEMS_COMMENTS_SUCCESS";
export const POST_NEWS_ITEMS_COMMENTS_ERROR = "POST_NEWS_ITEMS_COMMENTS_ERROR";

export const POST_NEWS_ITEMS_LIKES = "POST_NEWS_ITEMS_LIKES";
export const POST_NEWS_ITEMS_LIKES_SUCCESS = "POST_NEWS_ITEMS_LIKES_SUCCESS";
export const POST_NEWS_ITEMS_LIKES_ERROR = "POST_NEWS_ITEMS_LIKES_ERROR";

export const GET_NEWS_ITEMS_LIKES = "GET_NEWS_ITEMS_LIKES";
export const GET_NEWS_ITEMS_LIKES_SUCCESS = "GET_NEWS_ITEMS_LIKES_SUCCESS";
export const GET_NEWS_ITEMS_LIKES_ERROR = "GET_NEWS_ITEMS_LIKES_ERROR";

export const GET_GA_RECORDS = "GET_GA_RECORDS";
export const GET_GA_RECORDS_SUCCESS = "GET_GA_RECORDS_SUCCESS";
export const GET_GA_RECORDS_ERROR = "GET_GA_RECORDS_ERROR";

export const CLEAN_NEWSFEED = "CLEAN_NEWSFEED";
export const REFRESH_NEWSFEED = "REFRESH_NEWSFEED";

/* ARTICLE_LIST */
export const GET_ARTICLE_LIST = "GET_ARTICLE_LIST";
export const GET_ARTICLE_LIST_SUCCESS = "GET_ARTICLE_LIST_SUCCESS";
export const GET_ARTICLE_LIST_ERROR = "GET_ARTICLE_LIST_ERROR";


/* ARTICLE_DETAILS */
export const GET_ARTICLE = "GET_ARTICLE";
export const GET_ARTICLE_SUCCESS = "GET_ARTICLE_SUCCESS";
export const GET_ARTICLE_ERROR = "GET_ARTICLE_ERROR";
export const ADD_REPLY = "ADD_REPLY";
export const ADD_REPLY_SUCCESS = "ADD_REPLY_SUCCESS";
export const ADD_REPLY_ERROR = "ADD_REPLY_ERROR";
export const ARTICLE_DETAILS_CLEAR_DATA = "ARTICLE_DETAILS_CLEAR_DATA";
