
name: Build Android
on:
  push:
    branches: [ gh-actions ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Build Android Release
        run: cd android && chmod +x ./gradlew && ./gradlew assembleDebug && tree

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/
